#!/usr/bin/env python3
# encoding:utf8

import subprocess
from rofimenu import RofiMenu, ENC

class Connection:
    def __init__(self, ssid, signal) -> None:
        self.ssid = ssid
        self.signal = signal

    def __str__(self) -> str:

        if self.signal < 25:
            bars = "▂   "
        elif self.signal < 50:
            bars = "▂▄  "
        elif self.signal < 75:
            bars = "▂▄▆ "
        else:
            bars = "▂▄▆█"

        return f"{bars} {self.ssid}"


def get_conns():
    args = ["nmcli", "-g", "SSID,SIGNAL", "device", "wifi"]

    res = subprocess.run(args, capture_output=True, check=True, encoding=ENC)
    lines = res.stdout.strip().splitlines()

    for line in lines:
        ssid, signal = line.split(":")
        yield Connection(ssid, int(signal))


menu = RofiMenu("Wifi Menu", "$HOME/.config/rofi/menu.rasi", "Wifi")

for conn in get_conns():
    menu.add(str(conn), f"nmcli device wifi connect {conn.ssid}")

menu.add("   Settings", "nm-connection-editor")

menu.launch()
